packages = []
version = "0.1.1"


[splashscreen]
autoclose = true

[[interpreters]]
src = "/packages/pyodide/pyodide.mjs"
name = "pyo-24.1"
lang = "python"

[[fetch]]
from = "http://127.0.0.1:8000/"
files = ["components/div.py"]
