packages = []
version = "0.1.1"


[splashscreen]
autoclose = true

[[interpreters]]
src = "/packages/pyodide/pyodide.mjs"
name = "pyo-24.1"
lang = "python"

[[fetch]]
from = "http://localhost:8047/web/"
files = [
    "components/card.py",
    "components/form.py",
    "components/button.py",
    "components/label.py",
    "components/input.py",
    "components/svg.py",
    "components/div.py",
    "components/dropdown.py",
    "components/notes.py",
    "components/title.py",
    "components/side_bar.py",
    "elements/navbar.py",
    "elements/color_selector.py",
    "queries.py",
    "context.py",
    "views/gallery_view.py",
    "views/img_form_view.py",
    "views/edit.py",
]
