packages = []
version = "0.1.1"


[splashscreen]
autoclose = true

[[interpreters]]
src = "/packages/pyodide/pyodide.mjs"
name = "pyo"
lang = "python"

[[fetch]]
from = "https://local.dev:8062/"
files = [
    "senza/components/__init__.py",
    "senza/components/abase.py",
    "senza/components/div.py",
    "senza/components/anchor.py",
    "senza/components/button.py",
    "senza/components/form.py",
    "senza/components/img.py",
    "senza/components/input.py",
    "senza/components/label.py",
    "senza/components/h1.py",
    "senza/components/h2.py",
    "senza/components/h3.py",
    "senza/components/h4.py",
    "senza/components/h5.py",
    "senza/components/h6.py",
    "senza/components/ptag.py",
    "senza/components/select.py",
    "senza/components/svg.py",
    "senza/components/span.py",
    "senza/dom_router.py",
    "senza/websocket.py",
    "web/context.py",
    "web/app.py",
    "web/views/test_page.py",
]
